name: Ubuntu CI Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install
      run: |
        make install
    - name: setup
      run: |
        make setup
    - name: prepare
      run: |
        make prepare
    - name: configure
      run: |
        cmake . -Bbuild -DENABLE_COVERAGE=1 -DCMAKE_BUILD_TYPE=Coverage
    - name: build
      run: |
        cmake --build build -j4
    - name: test
      run: |
        cd build
        make CppTemplate_coverage
    - name: collect code coverage
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
